/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as PrizingRouteImport } from './routes/prizing'
import { Route as ChartRouteImport } from './routes/chart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as ToolsOptimizeRouteImport } from './routes/tools/optimize'
import { Route as ToolsGapRouteImport } from './routes/tools/gap'
import { Route as ToolsCheckRouteImport } from './routes/tools/check'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const PrizingRoute = PrizingRouteImport.update({
  id: '/prizing',
  path: '/prizing',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartRoute = ChartRouteImport.update({
  id: '/chart',
  path: '/chart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsOptimizeRoute = ToolsOptimizeRouteImport.update({
  id: '/optimize',
  path: '/optimize',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsGapRoute = ToolsGapRouteImport.update({
  id: '/gap',
  path: '/gap',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsCheckRoute = ToolsCheckRouteImport.update({
  id: '/check',
  path: '/check',
  getParentRoute: () => ToolsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chart': typeof ChartRoute
  '/prizing': typeof PrizingRoute
  '/results': typeof ResultsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/tools/check': typeof ToolsCheckRoute
  '/tools/gap': typeof ToolsGapRoute
  '/tools/optimize': typeof ToolsOptimizeRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chart': typeof ChartRoute
  '/prizing': typeof PrizingRoute
  '/results': typeof ResultsRoute
  '/tools/check': typeof ToolsCheckRoute
  '/tools/gap': typeof ToolsGapRoute
  '/tools/optimize': typeof ToolsOptimizeRoute
  '/tools': typeof ToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chart': typeof ChartRoute
  '/prizing': typeof PrizingRoute
  '/results': typeof ResultsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/tools/check': typeof ToolsCheckRoute
  '/tools/gap': typeof ToolsGapRoute
  '/tools/optimize': typeof ToolsOptimizeRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chart'
    | '/prizing'
    | '/results'
    | '/tools'
    | '/tools/check'
    | '/tools/gap'
    | '/tools/optimize'
    | '/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chart'
    | '/prizing'
    | '/results'
    | '/tools/check'
    | '/tools/gap'
    | '/tools/optimize'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/chart'
    | '/prizing'
    | '/results'
    | '/tools'
    | '/tools/check'
    | '/tools/gap'
    | '/tools/optimize'
    | '/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChartRoute: typeof ChartRoute
  PrizingRoute: typeof PrizingRoute
  ResultsRoute: typeof ResultsRoute
  ToolsRoute: typeof ToolsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prizing': {
      id: '/prizing'
      path: '/prizing'
      fullPath: '/prizing'
      preLoaderRoute: typeof PrizingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chart': {
      id: '/chart'
      path: '/chart'
      fullPath: '/chart'
      preLoaderRoute: typeof ChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/optimize': {
      id: '/tools/optimize'
      path: '/optimize'
      fullPath: '/tools/optimize'
      preLoaderRoute: typeof ToolsOptimizeRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/gap': {
      id: '/tools/gap'
      path: '/gap'
      fullPath: '/tools/gap'
      preLoaderRoute: typeof ToolsGapRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/check': {
      id: '/tools/check'
      path: '/check'
      fullPath: '/tools/check'
      preLoaderRoute: typeof ToolsCheckRouteImport
      parentRoute: typeof ToolsRoute
    }
  }
}

interface ToolsRouteChildren {
  ToolsCheckRoute: typeof ToolsCheckRoute
  ToolsGapRoute: typeof ToolsGapRoute
  ToolsOptimizeRoute: typeof ToolsOptimizeRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsCheckRoute: ToolsCheckRoute,
  ToolsGapRoute: ToolsGapRoute,
  ToolsOptimizeRoute: ToolsOptimizeRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChartRoute: ChartRoute,
  PrizingRoute: PrizingRoute,
  ResultsRoute: ResultsRoute,
  ToolsRoute: ToolsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
